project/coderslab/urls.py
from django.contrib import admin
from django.urls import path

from exercises_app import views
from football import views as football_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', views.articles),
    path('show-band/<int:band_id>/', views.show_band),
    path('table/', football_views.league_table),
    path('games/', football_views.games_played),
    path('add-game/', football_views.add_game),
    path('modify-team/', football_views.modify_team),
    # Cookies - zad 3
    path('set-favourite/', football_views.set_as_favourite),

    # Widoki klasowe - zad 3
    path('create-band/', views.BandCreateView.as_view()),
]

project/exercises_app/models.py
from django.db import models


# Create your models here.
class Band(models.Model):

    CHOICES = [
        (-1, 'not defined'),
        (0, 'rock'),
        (1, 'metal'),
        (2, 'pop'),
        (3, 'hip-hop'),
        (4, 'electronic'),
        (5, 'reggae'),
        (6, 'other')
    ]

    name = models.CharField(max_length=64)
    year = models.IntegerField(null=True)
    still_active = models.BooleanField(default=True)
    genre = models.IntegerField(choices=CHOICES, default=-1)


class Category(models.Model):
    name = models.CharField(max_length=64)
    description = models.TextField(null=True)


class Article(models.Model):

    CHOICES = [
        (0, 'in progress'),
        (1, 'waiting'),
        (2, 'published')
    ]

    title = models.CharField(max_length=128)
    author = models.CharField(max_length=64, null=True)
    content = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    status = models.IntegerField(choices=CHOICES, default=0)
    start_publish_date = models.DateTimeField(null=True)
    end_publish_date = models.DateTimeField(null=True)

    # zad 4
    categories = models.ManyToManyField('Category')


class Album(models.Model):

    CHOICES = [
        (0, 0),
        (1, 1),
        (2, 2),
        (3, 3),
        (4, 4),
        (5, 5),
    ]

    title = models.CharField(max_length=128)
    year = models.IntegerField()
    rating = models.IntegerField(choices=CHOICES)
    # relacje - zad 1
    band = models.ForeignKey('Band', on_delete=models.CASCADE)


# relacje - zad 2
class Song(models.Model):
    title = models.CharField(max_length=128)
    duration = models.TimeField(null=True)
    album = models.ForeignKey('Album', on_delete=models.CASCADE)

project/football/models.py
from django.db import models


class Game(models.Model):
    id = models.BigAutoField(primary_key=True)
    team_home = models.ForeignKey('Team', blank=True, null=True, related_name='games_home', on_delete=models.CASCADE)
    team_home_goals = models.BigIntegerField(blank=True, null=True)
    team_away = models.ForeignKey('Team', blank=True, null=True, related_name='games_away', on_delete=models.CASCADE)
    team_away_goals = models.BigIntegerField(blank=True, null=True)


class Team(models.Model):
    id = models.BigAutoField(primary_key=True)
    name = models.TextField()
    points = models.BigIntegerField(blank=True, null=True)

project/exercises_app/views.py
from django import views
from django.shortcuts import render, get_object_or_404

from exercises_app.models import Article

from exercises_app.models import Band

# Create your views here.
def articles(request):

    article_list = Article.objects.all()  # filter(status=2)

    return render(
        request,
        'articles.html',
        context={
            'article_list': article_list
        }
    )


def show_band(request, band_id):
    band = get_object_or_404(Band, id=band_id)

    return render(
        request,
        'show_band.html',
        context={
            'band': band
        }
    )


class BandCreateView(views.View):
    def get(self, request):
        return render(
            request,
            'create_band.html',
            context={
                'Band': Band,
            }
        )

    def post(self, request):
        name = request.POST.get('name')
        year = request.POST.get('year')
        still_active = request.POST.get('still_active')
        genre = request.POST.get('genre')

        if still_active == "on":
            still_active = True
        else:
            still_active = False

        Band.objects.create(
            name=name,
            year=year,
            still_active=still_active,
            genre=genre
        )

        return render(
            request,
            'message.html',
            context={
                'name': name,
            }
        )

project/football/views.py
from django.shortcuts import render, get_object_or_404, HttpResponse, redirect

from football.models import Team, Game

# Create your views here.
def league_table(request):
    try:
        fav_id = int(request.COOKIES.get('fav_team'))
    except (ValueError, TypeError):
        fav_id = None

    teams = Team.objects.order_by('-points')

    return render(
        request,
        'league_table.html',
        context={
            'teams': teams,
            'fav_id': fav_id
        }
    )


def games_played(request):
    # team_id = 1
    # Przekazywani inf... zad 3
    team_id = int(request.GET.get('id'))

    team = get_object_or_404(Team, id=team_id)

    games_home = Game.objects.filter(team_home=team)
    games_away = Game.objects.filter(team_away=team)

    games = games_home | games_away

    return render(
        request,
        'games.html',
        context={
            'games': games
        }
    )


# Formularze - zad 3
def add_game(request):
    if request.method == "GET":
        teams = Team.objects.all()

        host_team = request.session.get('host')

        return render(
            request,
            'add_game.html',
            context={
                'teams': teams,
                'host_team': host_team,
            }
        )

    elif request.method == "POST":
        try:
            team_home_id = int(request.POST.get('team_home'))
            team_home_goals = int(request.POST.get('team_home_goals'))

            team_away_id = int(request.POST.get('team_away'))
            team_away_goals = int(request.POST.get('team_away_goals'))
        except ValueError:
            return HttpResponse("Niepoprawne dane")

        if team_home_id == team_away_id:
            return HttpResponse("Zespoły nie mogą być takie same")

        team_home = get_object_or_404(Team, id=team_home_id)
        team_away = get_object_or_404(Team, id=team_away_id)

        request.session['host'] = team_home_id

        Game.objects.create(
            team_home=team_home,
            team_home_goals=team_home_goals,
            team_away=team_away,
            team_away_goals=team_away_goals
        )

        # Formularze - Zad 4
        if team_home_goals == team_away_goals:
            team_home.points += 1
            team_away.points += 1

            team_home.save()
            team_away.save()
        elif team_home_goals > team_away_goals:
            team_home.points += 3
            team_home.save()
        else:
            team_away.points += 3
            team_away.save()

        return redirect(f"/games/?id={team_home_id}")


def modify_team(request):
    try:
        team_id = int(request.GET.get('id'))
    except (ValueError, TypeError):
        return HttpResponse("Podano niepoprawne dane")

    team = get_object_or_404(Team, id=team_id)

    if request.method == "GET":
        return render(
            request,
            'modify_team.html',
            context={
                'team': team
            }
        )
    elif request.method == "POST":
        name = request.POST.get('name')
        try:
            points = request.POST.get('points')
        except (ValueError, TypeError):
            return HttpResponse("Podano niepoprawne dane")

        team.name = name
        team.points = points
        team.save()

        return redirect("/table/")


def set_as_favourite(request):
    try:
        team_id = int(request.GET.get('id'))
    except (ValueError, TypeError):
        return HttpResponse("Niepoprawny format danych")

    team = get_object_or_404(Team, id=team_id)

    response = render(
        request,
        'set_as_favourite.html',
        context={
            'team': team,
        }
    )
    response.set_cookie('fav_team', team_id)

    return response

project/exercises_app/templates/articles.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  {% for article in article_list %}
    <p>{{ article.title }} {{ article.author }} {{ article.date_added }}</p>
  {% endfor %}
</body>
</html>

project/exercises_app/templates/create_band.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  <form method="POST">{% csrf_token %}
    <input type="text" name="name" placeholder="nazwa">
    <input type="number" name="year" placeholder="rok powstania">
    <input type="checkbox" name="still_active">
    <select name="genre">
      {% for value, display in Band.CHOICES %}
        <option value="{{ value }}">{{ display }}</option>
      {% endfor %}
    </select>
    <input type="submit" value="Zapisz">
  </form>
</body>
</html>

project/exercises_app/templates/message.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  Zespół {{ name }} został pomyślnie zapisany w bazie danych!
</body>
</html>

project/exercises_app/templates/show_band.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  <h3>Nazwa: {{ band.name }}</h3>
  <h5>Rok: {{ band.year }}</h5>
  <h5>Gatunek: {{ band.get_genre_display }}</h5>
  <h5>Aktywny:
      {% if band.still_active == True %}
        Tak
      {% else %}
        Nie
      {% endif %}
  </h5>
</body>
</html>

project/football/templates/add_game.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  <form method="POST">{% csrf_token %}
      <label>Zespół gospodarzy:</label>
      <select name="team_home">

          {% for team in teams %}
            {% if team.id == host_team %}
                <option value="{{ team.id }}" selected>{{ team.name }}</option>
            {% else %}
                <option value="{{ team.id }}">{{ team.name }}</option>
            {% endif %}
          {% endfor %}

      </select>
      <input type="number" name="team_home_goals">

      <label>Zespół gości:</label>
      <select name="team_away">
          {% for team in teams %}
            <option value="{{ team.id }}">{{ team.name }}</option>
          {% endfor %}
      </select>
      <input type="number" name="team_away_goals">

      <input type="submit" value="Zapisz">
  </form>
</body>
</html>

project/football/templates/games.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        table, tr, td, th {
            border: solid;
            border-collapse: collapse;
            padding: 8px;
        }
    </style>

</head>
<body>
    <table>
        <tr>
            <th>Zespół gospodarza</th>
            <th>Zespół gościa</th>
            <th>Wynik</th>
        </tr>
        {% for game in games %}
            <tr>
                <td>{{ game.team_home.name }}</td>
                <td>{{ game.team_away.name }}</td>
                <td>{{ game.team_home_goals }}:{{ game.team_away_goals }}</td>
            </tr>
        {% endfor %}
    </table>
</body>
</html>

project/football/templates/league_table.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        table, tr, td {
            border: solid;
            border-collapse: collapse;
            padding: 8px;
        }
    </style>
</head>
<body>
  <table>
      {% for team in teams %}
        {% if team.id == fav_id %}
          <tr style="background-color: red;">
              {% else %}
          <tr>
        {% endif %}
              <td>{{ forloop.counter }}</td>
              {# Przekazywanie informacji ... zad 4 #}
              <td><a href="/games?id={{ team.id }}">{{ team.name }}</a>
              <a href="/set-favourite?id={{ team.id }}"><button>Zaznacz jako ulubiony</button></a>
              </td>
              <td>{{ team.points }}</td>
          </tr>
      {% endfor %}
  </table>
</body>
</html>

project/football/templates/modify_team.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  <form method="POST">{% csrf_token %}
      <input type="text" value="{{ team.name }}" name="name">
      <input type="number" value="{{ team.points }}" name="points">
      <input type="submit" value="Zapisz">
  </form>
</body>
</html>

project/football/templates/set_as_favourite.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  Ustawiono ulubiony zespół na: {{ team.name }}
</body>
</html>

project/football/templates/table_intro.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  <table style="border: solid; border-collapse: collapse;">

    <tr>
      <th style="border: solid; padding: 8px;">Imię</th>
      <th style="border: solid; padding: 8px;">Nazwisko</th>
    </tr>

    <tr>
      <td style="border: solid; padding: 8px;" >Jan</td>
      <td style="border: solid; padding: 8px;">Kowalski</td>
    </tr>

    <tr>
      <td style="border: solid; padding: 8px;">Adam</td>
      <td style="border: solid; padding: 8px;">Nowak</td>
    </tr>

  </table>
</body>
</html>